### ISSUE TITLE
lodash should be inside dependencies instead of devDependencies

### ISSUE THREAD

**Issue by mukumar-qasource** [jsrockstar132/angular2-acl#1]
`"devDependencies": {
    "lodash": "^4.13.1",
    "typings": "^1.3.0"
  },`

angular2-acl depends on lodash. Running **npm install** on parent project doesn't download **lodash** as angular2-acl nested dependency.

Do I need to make some adjustments in my package.json file to make it work ?

**Comment by jsrkstr** [comment]
I have moved lodash to dependencies. Should work for you now, Thanks

**Comment by mukumar-qasource** [comment]
I should have replied a little earlier :)

Many thanks for your efforts. It now works the way I needed.
