### ISSUE TITLE
Angular2 docs

### ISSUE THREAD

**Issue by scheung38** [jsrockstar132/angular2-acl#2]
Documentation is pointing toward angular-acl, but is that still the case now it is using Typescript Angular2?

**Comment by jsrkstr** [comment]
Hi, Sorry for delayed reply. Yes, this service is written in typescript for Angular 2 applications. You can refer the documentation for angular-acl.

**Comment by anandangular** [comment]
It based on angular2 or angularjs ????????????

**Comment by jsrkstr** [comment]
Hi Anand, It's written in typescript for Angular 2 applications
